# Generated by Django 5.2.17 on 2026-09-18 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_tryon_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaGuardada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(blank=True, default='', max_length=10)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('captura', models.ImageField(blank=True, null=True, upload_to='tryon/capturas/%Y/%m/')),
                ('captura_base64', models.TextField(blank=True, default='', help_text='Fallback base64 si offline')),
                ('video', models.FileField(blank=True, null=True, upload_to='tryon/videos/%Y/%m/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='catalog.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_tryon', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'prueba guardada',
                'verbose_name_plural': 'pruebas guardadas',
                'ordering': ('-creado_en',),
            },
        ),
    ]
