# Generated by Django 5.2.17 on 2026-09-17 17:20

from django.db import migrations, models


def convertir_altura_cm_a_metros(apps, schema_editor):
    Usuario = apps.get_model("users", "Usuario")
    for u in Usuario.objects.exclude(altura__isnull=True):
        try:
            val = float(u.altura)
            if val > 3:  # estaba en cm
                u.altura = round(val / 100, 2)
                u.save(update_fields=["altura"])
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cu16_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altura en metros', max_digits=4, null=True),
        ),
        migrations.RunPython(convertir_altura_cm_a_metros, migrations.RunPython.noop),
    ]
