# Generated by Django 5.2.17 on 2026-09-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('vestidos', 'Vestidos'), ('blusas', 'Blusas'), ('faldas', 'Faldas'), ('pantalones', 'Pantalones'), ('jeans', 'Jeans'), ('conjuntos', 'Conjuntos'), ('ropa_interior', 'Ropa interior'), ('abrigos', 'Abrigos / Chaquetas'), ('tops', 'Tops'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción corta')),
                ('detalle', models.TextField(blank=True, help_text='Detalle largo, materiales, cuidados')),
                ('color', models.CharField(help_text='Ej: Rojo, Negro, Beige', max_length=50)),
                ('talla', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('UNICA', 'Talla única'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46')], max_length=10)),
                ('precio_centavos', models.PositiveIntegerField(help_text='Precio en centavos de Bs. Ej: 19900 = 199.00 Bs')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen subida como archivo', null=True, upload_to='productos/%Y/%m/')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ('-creado_en',),
            },
        ),
    ]
