# Generated by Django 5.2.17 on 2026-09-13 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ('nombre',),
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('vestidos', 'Vestidos'), ('blusas', 'Blusas'), ('faldas', 'Faldas'), ('pantalones', 'Pantalones'), ('jeans', 'Jeans'), ('conjuntos', 'Conjuntos'), ('ropa_interior', 'Ropa interior'), ('abrigos', 'Abrigos / Chaquetas'), ('tops', 'Tops'), ('otro', 'Otro')], default='vestidos', max_length=30),
        ),
        migrations.CreateModel(
            name='ProductoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_productos', to='catalog.categoria')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_categorias', to='catalog.producto')),
            ],
            options={
                'verbose_name': 'producto - categoría',
                'verbose_name_plural': 'productos - categorías',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='productos', through='catalog.ProductoCategoria', to='catalog.categoria'),
        ),
        migrations.AddConstraint(
            model_name='productocategoria',
            constraint=models.UniqueConstraint(fields=('producto', 'categoria'), name='unique_producto_categoria'),
        ),
    ]
