# Generated by Django 5.2.17 on 2026-09-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_categoria_alter_producto_categoria_productocategoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calificación 0-5', max_digits=3),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, default='', help_text='Marca del producto', max_length=80),
        ),
        migrations.AddField(
            model_name='producto',
            name='popularidad',
            field=models.PositiveIntegerField(default=0, help_text='Veces agregado al carrito / comprado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_cuerpo',
            field=models.CharField(choices=[('reloj_arena', 'Reloj de arena'), ('rectangulo', 'Rectángulo'), ('triangulo', 'Triángulo'), ('triangulo_invertido', 'Triángulo invertido'), ('ovalo', 'Óvalo'), ('todos', 'Todos los cuerpos')], default='todos', max_length=30),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_venta',
            field=models.CharField(choices=[('menor', 'Menor (detal)'), ('mayor', 'Mayor (por mayor)')], default='menor', max_length=10),
        ),
    ]
