# Generated by Django 5.2.17 on 2026-09-17 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_cu04_catalog_filters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('direccion', models.CharField(blank=True, default='', max_length=200)),
                ('ciudad', models.CharField(blank=True, default='', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='cuidados',
            field=models.CharField(blank=True, default='', help_text='Ej: Lavar a mano, no planchar', max_length=255),
        ),
        migrations.AddField(
            model_name='producto',
            name='origen',
            field=models.CharField(blank=True, default='', help_text='Ej: Bolivia, Importado', max_length=80),
        ),
        migrations.AddField(
            model_name='producto',
            name='tela',
            field=models.CharField(blank=True, default='', help_text='Ej: Algodón 100%, Poliéster', max_length=120),
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(max_length=80)),
                ('calificacion', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opiniones', to='catalog.producto')),
            ],
            options={
                'verbose_name': 'opinión',
                'verbose_name_plural': 'opiniones',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/%Y/%m/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='catalog.producto')),
            ],
            options={
                'verbose_name': 'imagen de producto',
                'verbose_name_plural': 'galería de productos',
                'ordering': ('orden', 'id'),
            },
        ),
        migrations.CreateModel(
            name='NotificacionStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('talla', models.CharField(blank=True, default='', max_length=10)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('notificado', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_stock', to='catalog.producto')),
            ],
            options={
                'verbose_name': 'notificación de stock',
                'verbose_name_plural': 'notificaciones de stock',
                'constraints': [models.UniqueConstraint(fields=('producto', 'email', 'talla', 'color'), name='unique_notif_stock')],
            },
        ),
        migrations.CreateModel(
            name='StockSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_sucursales', to='catalog.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.sucursal')),
            ],
            options={
                'verbose_name': 'stock por sucursal',
                'verbose_name_plural': 'stocks por sucursal',
                'constraints': [models.UniqueConstraint(fields=('producto', 'sucursal'), name='unique_stock_sucursal')],
            },
        ),
    ]
