# Generated by Django 5.2.17 on 2026-09-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_cu05_detail'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stocksucursal',
            name='unique_stock_sucursal',
        ),
        migrations.AddField(
            model_name='stocksucursal',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Color específico', max_length=50),
        ),
        migrations.AddField(
            model_name='stocksucursal',
            name='talla',
            field=models.CharField(blank=True, default='', help_text='Talla específica, vacío = stock total', max_length=10),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='horario',
            field=models.CharField(blank=True, default='Lun-Sáb 09:00-19:00', max_length=100),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='stocksucursal',
            constraint=models.UniqueConstraint(fields=('producto', 'sucursal', 'talla', 'color'), name='unique_stock_sucursal'),
        ),
    ]
