# Generated by Django 5.2.17 on 2026-09-17 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_cu06_disponibilidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(blank=True, default='', max_length=10)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('motivo', models.CharField(choices=[('danado', 'Dañado'), ('extraviado', 'Extraviado'), ('vencido', 'Vencido'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mermas', to='catalog.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mermas', to='catalog.sucursal')),
            ],
            options={
                'verbose_name': 'merma',
                'verbose_name_plural': 'mermas',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(blank=True, default='', max_length=10)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('completado', 'Completado'), ('pendiente', 'Pendiente aprobación')], default='completado', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados_destino', to='catalog.sucursal')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados_origen', to='catalog.sucursal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados', to='catalog.producto')),
            ],
            options={
                'verbose_name': 'traslado',
                'verbose_name_plural': 'traslados',
                'ordering': ('-creado_en',),
            },
        ),
    ]
