# Generated by Django 5.2.17 on 2026-09-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_cu16_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='modelo_3d',
            field=models.FileField(blank=True, null=True, upload_to='tryon/modelos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tryon_escala',
            field=models.JSONField(blank=True, default=dict, help_text='Escala por talla ej {"XS":0.9}'),
        ),
    ]
