# Generated by Django 5.2.17 on 2026-09-19 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_tryon_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksucursal',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=3, help_text='Alerta si stock <= mínimo'),
        ),
        migrations.CreateModel(
            name='Apartado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(blank=True, default='', max_length=10)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado'), ('completado', 'Completado')], default='activo', max_length=20)),
                ('expira_en', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartados', to='catalog.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartados', to='catalog.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'apartado',
                'verbose_name_plural': 'apartados',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('online', 'Online'), ('tienda', 'Tienda física')], default='online', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('listo', 'Listo para entrega'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('pago_metodo', models.CharField(choices=[('qr', 'QR'), ('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo')], default='tarjeta', max_length=20)),
                ('total_centavos', models.PositiveIntegerField(default=0)),
                ('qr_data', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='catalog.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('talla', models.CharField(blank=True, default='', max_length=10)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_centavos', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.producto')),
            ],
        ),
    ]
