# Generated by Django 5.2.17 on 2026-09-13 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_categoria_alter_producto_categoria_productocategoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: BIENVENIDA10', max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto', 'Monto fijo (Bs)')], default='porcentaje', max_length=10)),
                ('valor', models.PositiveIntegerField(help_text='Si porcentaje: 10 = 10%. Si monto: centavos (1000 = 10 Bs)')),
                ('activo', models.BooleanField(default=True)),
                ('usos_max', models.PositiveIntegerField(blank=True, help_text='Null = ilimitado', null=True)),
                ('usos_actual', models.PositiveIntegerField(default=0)),
                ('expira_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'cupón',
                'verbose_name_plural': 'cupones',
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='cart.coupon')),
            ],
            options={
                'verbose_name': 'carrito',
                'verbose_name_plural': 'carritos',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('UNICA', 'Talla única'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46')], max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_centavos', models.PositiveIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.producto')),
            ],
            options={
                'verbose_name': 'ítem de carrito',
                'verbose_name_plural': 'ítems de carrito',
                'ordering': ('-creado_en',),
                'constraints': [models.UniqueConstraint(fields=('cart', 'producto', 'talla', 'color'), name='unique_cart_producto_variante')],
            },
        ),
    ]
